### ISSUE TITLE
Darkened map usage

### ISSUE THREAD

**Issue by ooosssay** [pkrasicki/issviewer#31]
Hello, I came across an issue on dark mode for the openstreetmap map and saw your comment. I was wondering on your thought of allowing an app to use the darkened map in your website as a basemap. Note that I’m not the developer just asking if you were okay.

Also the app in question has a ISC license.
Also is there any differences with how fast the tiles update with this map and the original?

Also sorry for asking here as I could not find any other way of contacting you.

**Comment by pkrasicki** [comment]
Hi, what do you mean by allowing an app to use the map on my website? I use regular OpenStreetMap and I've only modified the way it looks with a few lines of CSS code. The developer of the app can probably do the same and get a similar result (it shouldn't be difficult). So if you are asking if they can copy the CSS code for the map tiles, then sure, I don't mind it. But if they want to copy a significant amount of my JavaScript code, then they would have to use AGPL license for their app.

>Also is there any differences with how fast the tiles update with this map and the original?

There is no difference to how fast the tiles update, because it is the original map with just a filter applied on top using CSS.

**Comment by ooosssay** [comment]
Ohh okay I see (I am not well versed on these things)
